import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');
export const CANVAS_ASPECT = 4 / 5;
export const CANVAS_WIDTH = (SCREEN_WIDTH - 42) * 0.9;
export const CANVAS_HEIGHT = CANVAS_WIDTH / CANVAS_ASPECT;
export const TEXT_BASE_FONT_SIZE = 32;
export const SHEET_MIN_HEIGHT = Math.min(320, Math.max(240, SCREEN_HEIGHT * 0.4));
export const SHEET_MAX_HEIGHT = SCREEN_HEIGHT * 0.65;

const COLORS = {
  bg: '#F7F8FB',
  surface: '#FFFFFF',
  surfaceAlt: '#F1F3F7',
  border: '#E4E7EE',
  text: '#0F172A',
  muted: '#667085',
  mutedLight: '#98A2B3',
  accent: '#2563EB',
  accentStrong: '#1D4ED8',
  accentSoft: '#EEF2FF',
  accentTint: 'rgba(37, 99, 235, 0.12)',
  danger: '#EF4444',
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, backgroundColor: COLORS.surface, borderBottomWidth: 1, borderColor: COLORS.border },
  headerTitle: { fontWeight: '800', fontSize: 16, color: COLORS.text },
  headerBtnPrimary: { backgroundColor: COLORS.accent, paddingHorizontal: 16, paddingVertical: 6, borderRadius: 20, marginRight: 8 },
  headerBtnTextPrimary: { color: COLORS.surface, fontWeight: 'bold', fontSize: 12 },
  headerIconBtn: { padding: 6, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  backIcon: { fontSize: 28, color: COLORS.text, marginTop: Platform.select({ ios: -2, android: 0 }) },
  previewContainer: {
    flex: 1,
    paddingTop: 12,
    // Reserve space for the collapsed sheet so the canvas doesn't shift when the sheet expands.
    paddingBottom: SHEET_MIN_HEIGHT ,
  },
  previewStage: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  exportHidden: {
    position: 'absolute',
    top: -10000,
    left: -10000,
    opacity: 0,
    pointerEvents: 'none',
  },
  floatingTools: { position: 'absolute', top: 30, right: 30, flexDirection: 'row', gap: 10, zIndex: 10 },
  circleBtn: { width: 44, height: 44, borderRadius: 22, backgroundColor: COLORS.surface, alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOpacity: 0.12, elevation: 6 },
  loaderOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(255,255,255,0.7)', justifyContent: 'center', alignItems: 'center', zIndex: 50 },
  loaderText: { marginTop: 10, fontWeight: '800', color: COLORS.accent },
  emptyState: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24 },
  emptyTitle: { fontSize: 18, fontWeight: '800', color: COLORS.text, marginBottom: 6 },
  emptySub: { fontSize: 13, fontWeight: '600', color: COLORS.muted, marginBottom: 16, textAlign: 'center' },
  emptyBtn: { backgroundColor: COLORS.text, paddingHorizontal: 18, paddingVertical: 10, borderRadius: 999 },
  emptyBtnText: { color: COLORS.surface, fontWeight: '800' },
  sheet: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: COLORS.surface, borderTopLeftRadius: 28, borderTopRightRadius: 28, shadowColor: '#0B1220', shadowOpacity: 0.08, shadowRadius: 18, elevation: 20, zIndex: 100 },
  grabberArea: { width: '100%', height: 30, alignItems: 'center', justifyContent: 'center' },
  grabber: { width: 44, height: 4, backgroundColor: COLORS.border, borderRadius: 2 },
  tabRow: { flexDirection: 'row', backgroundColor: COLORS.surfaceAlt, borderRadius: 16, padding: 4, marginBottom: 15, borderWidth: 1, borderColor: COLORS.border },
  tabBtn: { flex: 1, paddingVertical: 8, alignItems: 'center', borderRadius: 8 },
  tabBtnActive: { backgroundColor: COLORS.surface, shadowColor: '#0B1220', shadowOpacity: 0.06, shadowRadius: 6, elevation: 1, borderWidth: 1, borderColor: COLORS.border },
  tabText: { fontSize: 10, fontWeight: '700', color: COLORS.mutedLight, textTransform: 'uppercase' },
  tabTextActive: { color: COLORS.text },
  pillBtn: { paddingHorizontal: 14, paddingVertical: 7, borderRadius: 999, marginRight: 6, borderWidth: 1, borderColor: 'transparent' },
  pillBtnActive: { backgroundColor: COLORS.accent, borderColor: COLORS.accentStrong },
  pillBtnInactive: { backgroundColor: COLORS.surfaceAlt, borderColor: COLORS.border },
  pillBtnMagic: { backgroundColor: COLORS.accentStrong },
  pillTextActive: { color: COLORS.surface, fontSize: 10, fontWeight: 'bold', textTransform: 'uppercase' },
  pillTextInactive: { color: COLORS.mutedLight, fontSize: 10, fontWeight: 'bold', textTransform: 'uppercase' },
  pillTextMagic: { color: COLORS.surface, fontSize: 10, fontWeight: 'bold', textTransform: 'uppercase' },
  sectionTitle: { fontSize: 12, fontWeight: '800', color: COLORS.mutedLight, textTransform: 'uppercase', marginBottom: 10 },
  modeIcon: { width: 56, height: 56, borderRadius: 16, backgroundColor: COLORS.surfaceAlt, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: COLORS.border },
  modeIconActive: { backgroundColor: COLORS.accentSoft, borderWidth: 2, borderColor: COLORS.accent },
  label: { fontSize: 10, fontWeight: '700', color: COLORS.muted, marginTop: 10, marginBottom: 4, textTransform: 'uppercase' },
  toolTab: { flex: 1, paddingVertical: 8, alignItems: 'center', borderRadius: 8 },
  toolTabActive: { backgroundColor: COLORS.accentSoft, shadowColor: '#0B1220', shadowOpacity: 0.04, shadowRadius: 4, elevation: 1, borderWidth: 1, borderColor: COLORS.accentTint },
  actionBtn: { padding: 10, backgroundColor: COLORS.surfaceAlt, borderRadius: 10, alignItems: 'center', flex: 1, borderWidth: 1, borderColor: COLORS.border },
  toolBtn: { padding: 8, backgroundColor: COLORS.surfaceAlt, borderRadius: 8, borderWidth: 1, borderColor: COLORS.border },
  toolBtnActive: { backgroundColor: COLORS.accent, borderColor: COLORS.accentStrong },
  toolText: { fontSize: 12, fontWeight: '800', color: COLORS.muted },
  toolTextActive: { color: COLORS.surface },
  loadingContainer: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  skiaView: { borderRadius: 20, overflow: 'hidden' },
  canvas: { flex: 1, backgroundColor: 'transparent' },
  sheetPadding: { paddingHorizontal: 20 },
  sheetContent: { paddingHorizontal: 20, paddingBottom: 50 },
  subTabRow: { flexDirection: 'row', gap: 10, borderBottomWidth: 1, borderColor: COLORS.border, paddingBottom: 10, marginBottom: 15 },
  sliderContainer: { marginBottom: 15 },
  modeScroll: { marginBottom: 15 },
  modeItem: { alignItems: 'center', marginRight: 15 },
  modeLabel: { fontSize: 10, marginTop: 6, color: COLORS.muted },
  modeLabelActive: { color: COLORS.text, fontWeight: '700' },
  optionRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 6, marginBottom: 6 },
  optionLabel: { fontSize: 10, fontWeight: '700', color: COLORS.muted, textTransform: 'uppercase' },
  paletteContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  colorDot: { width: 30, height: 30, borderRadius: 15, borderWidth: 1, borderColor: COLORS.border },
  colorPickerWrap: { marginTop: 6 },
  colorPicker: { gap: 12 },
  colorPickerPreview: { borderRadius: 14, overflow: 'hidden' },
  colorPickerPanel: { borderRadius: 14, overflow: 'hidden', height: 180 },
  colorPickerSlider: { borderRadius: 999, overflow: 'hidden' },
  colorPickerSwatches: { marginTop: 4 },
  gradientWrap: { marginTop: 6 },
  gradientStopsRow: { flexDirection: 'row', gap: 10, marginBottom: 10 },
  gradientStopBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 10, paddingHorizontal: 12, borderRadius: 12, backgroundColor: COLORS.surfaceAlt, borderWidth: 1, borderColor: COLORS.border },
  gradientStopBtnActive: { backgroundColor: COLORS.accentSoft, borderColor: COLORS.accent },
  gradientStopSwatch: { width: 18, height: 18, borderRadius: 6, borderWidth: 1, borderColor: 'rgba(0,0,0,0.12)' },
  gradientStopText: { fontSize: 12, fontWeight: '800', color: COLORS.muted },
  gradientStopTextActive: { color: COLORS.text },
  bgToolsRow: { flexDirection: 'row', gap: 10, marginTop: 5 },
  subjectToolsRow: { flexDirection: 'row', backgroundColor: COLORS.surfaceAlt, padding: 4, borderRadius: 12, marginBottom: 15, borderWidth: 1, borderColor: COLORS.border },
  subjectVariantWrap: { marginBottom: 10 },
  subjectVariantRow: { flexDirection: 'row', gap: 8 },
  subjectToolText: { fontWeight: '700' },
  subjectToolTextActive: { color: COLORS.accentStrong },
  subjectToolTextInactive: { color: COLORS.mutedLight },
  centerResetRow: { flexDirection: 'row', gap: 10, marginTop: 10 },
  addTextBtn: { backgroundColor: COLORS.accent, borderRadius: 12, paddingVertical: 12 },
  addTextBtnLabel: { color: COLORS.surface, fontWeight: '900' },
  editTextContainer: { marginTop: 14, padding: 12, backgroundColor: COLORS.surface, borderRadius: 14, borderWidth: 1, borderColor: COLORS.border },
  textEditInput: { height: 44, borderRadius: 12, paddingHorizontal: 12, backgroundColor: COLORS.surfaceAlt, color: COLORS.text, fontWeight: '800', borderWidth: 1, borderColor: COLORS.border },
  textActionsRow: { flexDirection: 'row', gap: 10, marginBottom: 12 },
  textActionBtn: { flex: 1, paddingVertical: 12, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  textActionBtnPrimary: { backgroundColor: COLORS.text },
  textActionBtnPrimaryLabel: { color: COLORS.surface, fontWeight: '900' },
  textActionBtnDanger: { backgroundColor: '#FEE2E2' },
  textActionBtnDangerLabel: { color: '#B91C1C', fontWeight: '900' },
  textColorRow: { flexDirection: 'row', gap: 8, paddingVertical: 6 },
  textColorDot: { width: 30, height: 30, borderRadius: 15, borderWidth: 1, borderColor: 'rgba(15, 23, 42, 0.12)' },
  textColorDotActive: { borderWidth: 2, borderColor: COLORS.accentStrong },
  noTextLabel: { marginTop: 20, color: COLORS.mutedLight, textAlign: 'center' },
  marginTop10: { marginTop: 10 },
  modalOverlay: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(2, 8, 23, 0.45)' },
  modalContent: { width: '80%', backgroundColor: COLORS.surface, borderRadius: 15, padding: 20 },
  modalTitle: { fontSize: 16, fontWeight: 'bold', marginBottom: 10 },
  modalInput: { borderWidth: 1, borderColor: COLORS.border, borderRadius: 8, padding: 10, maxHeight: 100, marginBottom: 15 },
  modalButtons: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10 },
  modalBtnCancel: { padding: 10 },
  modalBtnTextCancel: { color: COLORS.danger },
  modalBtnSave: { backgroundColor: COLORS.accent, paddingVertical: 10, paddingHorizontal: 20, borderRadius: 8 },
  modalBtnTextSave: { color: COLORS.surface, fontWeight: 'bold' },
});
