import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');
export const CANVAS_ASPECT = 4 / 5;
export const CANVAS_WIDTH = SCREEN_WIDTH - 32;
export const CANVAS_HEIGHT = CANVAS_WIDTH / CANVAS_ASPECT;
export const TEXT_BASE_FONT_SIZE = 32;
export const SHEET_MIN_HEIGHT = 320;
export const SHEET_MAX_HEIGHT = SCREEN_HEIGHT * 0.65;


export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f3f4f6' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, backgroundColor: 'white', borderBottomWidth: 1, borderColor: '#e5e7eb' },
  headerTitle: { fontWeight: '800', fontSize: 16 },
  headerBtnPrimary: { backgroundColor: 'black', paddingHorizontal: 16, paddingVertical: 6, borderRadius: 20 },
  headerBtnTextPrimary: { color: 'white', fontWeight: 'bold', fontSize: 12 },
  headerIconBtn: { padding: 6, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  previewContainer: { flex: 1, alignItems: 'center', justifyContent: 'flex-start', paddingTop: 20 },
  floatingTools: { position: 'absolute', top: 30, right: 30, flexDirection: 'row', gap: 10, zIndex: 10 },
  circleBtn: { width: 44, height: 44, borderRadius: 22, backgroundColor: 'white', alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOpacity: 0.12, elevation: 6 },
  loaderOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(255,255,255,0.7)', justifyContent: 'center', alignItems: 'center', zIndex: 50 },
  loaderText: { marginTop: 10, fontWeight: '800', color: '#3b82f6' },
  sheet: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: 'white', borderTopLeftRadius: 24, borderTopRightRadius: 24, shadowColor: '#000', shadowOpacity: 0.15, shadowRadius: 10, elevation: 20, zIndex: 100 },
  grabberArea: { width: '100%', height: 30, alignItems: 'center', justifyContent: 'center' },
  grabber: { width: 40, height: 4, backgroundColor: '#e5e7eb', borderRadius: 2 },
  tabRow: { flexDirection: 'row', backgroundColor: '#f3f4f6', borderRadius: 12, padding: 4, marginBottom: 15 },
  tabBtn: { flex: 1, paddingVertical: 8, alignItems: 'center', borderRadius: 8 },
  tabBtnActive: { backgroundColor: 'white', shadowColor: '#000', shadowOpacity: 0.05 },
  tabText: { fontSize: 10, fontWeight: '700', color: '#999', textTransform: 'uppercase' },
  tabTextActive: { color: '#000' },
  pillBtn: { paddingHorizontal: 12, paddingVertical: 4, borderRadius: 20, marginRight: 5 },
  pillBtnActive: { backgroundColor: '#000' },
  pillBtnInactive: { backgroundColor: '#f3f4f6' },
  pillBtnMagic: { backgroundColor: '#4f46e5' },
  pillTextActive: { color: 'white', fontSize: 10, fontWeight: 'bold', textTransform: 'uppercase' },
  pillTextInactive: { color: '#999', fontSize: 10, fontWeight: 'bold', textTransform: 'uppercase' },
  pillTextMagic: { color: 'white', fontSize: 10, fontWeight: 'bold', textTransform: 'uppercase' },
  sectionTitle: { fontSize: 12, fontWeight: '800', color: '#9ca3af', textTransform: 'uppercase', marginBottom: 10 },
  modeIcon: { width: 48, height: 48, borderRadius: 12, backgroundColor: '#f3f4f6', alignItems: 'center', justifyContent: 'center' },
  modeIconActive: { backgroundColor: '#dbeafe', borderWidth: 2, borderColor: '#3b82f6' },
  label: { fontSize: 10, fontWeight: '700', color: '#6b7280', marginTop: 10, marginBottom: 4, textTransform: 'uppercase' },
  toolTab: { flex: 1, paddingVertical: 8, alignItems: 'center', borderRadius: 8 },
  toolTabActive: { backgroundColor: 'white', shadowColor: '#000', shadowOpacity: 0.05 },
  actionBtn: { padding: 10, backgroundColor: '#f3f4f6', borderRadius: 8, alignItems: 'center', flex: 1 },
  toolBtn: { padding: 8, backgroundColor: '#eee', borderRadius: 6 },
  toolBtnActive: { backgroundColor: '#3b82f6' },
  loadingContainer: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  skiaView: { borderRadius: 20, overflow: 'hidden' },
  canvas: { flex: 1, backgroundColor: 'white' },
  sheetPadding: { paddingHorizontal: 20 },
  sheetContent: { paddingHorizontal: 20, paddingBottom: 50 },
  subTabRow: { flexDirection: 'row', gap: 10, borderBottomWidth: 1, borderColor: '#f3f4f6', paddingBottom: 10, marginBottom: 15 },
  sliderContainer: { marginBottom: 15 },
  magicContainer: { backgroundColor: '#e0e7ff', padding: 15, borderRadius: 15, borderWidth: 1, borderColor: '#c7d2fe' },
  magicTitle: { fontSize: 12, fontWeight: '800', color: '#4338ca', marginBottom: 10, textTransform: 'uppercase' },
  magicInput: { backgroundColor: 'white', borderRadius: 10, padding: 12, height: 80, textAlignVertical: 'top', marginBottom: 10 },
  magicBtn: { backgroundColor: '#4f46e5', padding: 12, borderRadius: 10, alignItems: 'center' },
  magicBtnText: { color: 'white', fontWeight: 'bold', textTransform: 'uppercase', fontSize: 12 },
  modeScroll: { marginBottom: 15 },
  modeItem: { alignItems: 'center', marginRight: 15 },
  modeLabel: { fontSize: 10, marginTop: 4 },
  paletteContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  colorDot: { width: 30, height: 30, borderRadius: 15, borderWidth: 1, borderColor: '#ddd' },
  bgToolsRow: { flexDirection: 'row', gap: 10, marginTop: 5 },
  subjectToolsRow: { flexDirection: 'row', backgroundColor: '#f3f4f6', padding: 4, borderRadius: 10, marginBottom: 15 },
  subjectToolText: { fontWeight: '700' },
  subjectToolTextActive: { color: 'black' },
  subjectToolTextInactive: { color: '#999' },
  centerResetRow: { flexDirection: 'row', gap: 10, marginTop: 10 },
  addTextBtn: { backgroundColor: '#3b82f6' },
  addTextBtnLabel: { color: 'white', fontWeight: 'bold' },
  editTextContainer: { marginTop: 15, padding: 10, backgroundColor: '#f9f9f9', borderRadius: 10 },
  textColorRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginTop: 5 },
  textColorDot: { width: 24, height: 24, borderRadius: 12, borderWidth: 1, borderColor: '#ddd' },
  deleteTextBtn: { marginTop: 10, padding: 10, backgroundColor: '#fee2e2', borderRadius: 8, alignItems: 'center' },
  deleteTextLabel: { color: 'red', fontWeight: 'bold' },
  noTextLabel: { marginTop: 20, color: '#999', textAlign: 'center' },
  marginTop10: { marginTop: 10 },
  modalOverlay: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.5)' },
  modalContent: { width: '80%', backgroundColor: 'white', borderRadius: 15, padding: 20 },
  modalTitle: { fontSize: 16, fontWeight: 'bold', marginBottom: 10 },
  modalInput: { borderWidth: 1, borderColor: '#eee', borderRadius: 8, padding: 10, maxHeight: 100, marginBottom: 15 },
  modalButtons: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10 },
  modalBtnCancel: { padding: 10 },
  modalBtnTextCancel: { color: 'red' },
  modalBtnSave: { backgroundColor: '#3b82f6', paddingVertical: 10, paddingHorizontal: 20, borderRadius: 8 },
  modalBtnTextSave: { color: 'white', fontWeight: 'bold' },
});
